// Fetch the full Citybus network from data.gov.hk and emit src/bus/generated.js:
//   API_STOPS: stopId -> {la, lo, zh, en}
//   API_ROUTES: [{id, dA:[zh,en], dB:[zh,en], o:[stopId...], i:[stopId...]}]
// Run: node scripts/gen-bus-net.mjs
import { writeFileSync } from 'node:fs';

const API = 'https://rt.data.gov.hk/v2/transport/citybus';
const jget = async url => {
  for (let t = 0; t < 4; t++) {
    try {
      const r = await fetch(url);
      if (r.ok) return r.json();
    } catch { /* retry */ }
    await new Promise(r => setTimeout(r, 400 * (t + 1)));
  }
  return null;
};
async function mapAll(items, n, fn) {
  const out = new Array(items.length);
  let i = 0;
  await Promise.all(Array(n).fill(0).map(async () => {
    while (i < items.length) { const k = i++; out[k] = await fn(items[k], k); }
  }));
  return out;
}

const list = await jget(`${API}/route/CTB`);
const routes = list.data;
console.log('routes:', routes.length);

const routeData = await mapAll(routes, 10, async r => {
  const [o, i] = await Promise.all([
    jget(`${API}/route-stop/CTB/${encodeURIComponent(r.route)}/outbound`),
    jget(`${API}/route-stop/CTB/${encodeURIComponent(r.route)}/inbound`),
  ]);
  const sort = d => (d?.data ?? []).sort((a, b) => a.seq - b.seq).map(s => s.stop);
  return { id: r.route, dA: [r.orig_tc, r.orig_en], dB: [r.dest_tc, r.dest_en], o: sort(o), i: sort(i) };
});
const ok = routeData.filter(r => r.o.length + r.i.length > 0);
console.log('routes with stops:', ok.length, ' skipped:', routes.length - ok.length);

const ids = [...new Set(ok.flatMap(r => [...r.o, ...r.i]))];
console.log('unique stops:', ids.length);
const stops = await mapAll(ids, 12, async id => {
  const d = await jget(`${API}/stop/${id}`);
  const s = d?.data;
  return s ? [id, { la: +s.lat, lo: +s.long, zh: s.name_tc, en: s.name_en }] : null;
});
const API_STOPS = Object.fromEntries(stops.filter(Boolean));
console.log('stops resolved:', Object.keys(API_STOPS).length);

const js = `// GENERATED by scripts/gen-bus-net.mjs — Citybus open data (data.gov.hk).
// ${new Date().toISOString()} — ${ok.length} routes, ${Object.keys(API_STOPS).length} stops.
export const API_STOPS = ${JSON.stringify(API_STOPS)};
export const API_ROUTES = ${JSON.stringify(ok)};
`;
writeFileSync(new URL('../src/bus/generated.js', import.meta.url), js);
console.log('wrote src/bus/generated.js', (js.length / 1024 / 1024).toFixed(2), 'MB');
