// Real Citybus LECIP onboard-announcement stop names, harvested from the
// documented {{CTBSR}} data on hkbus.fandom.com — where the spoken/displayed
// name differs from the flag or the open-data API string (landmark chains,
// shopping centres, swapped direction pairs). Keyed by stop id.
export const ANNOUNCE = {
  '000929': ['砵典乍街、中環站', 'Pottinger Street, Central Station'],
  '000931': ['皇仁書院、維多利亞公園、火龍徑', 'Queen\'s College, Victoria Park, Fire Dragon Path'],
  '000932': ['禾輋邨、沙田運動場', 'Wo Che Estate, Sha Tin Sports Ground'],
  '000933': ['瀝源邨、源禾路體育館', 'Lek Yuen Estate, Yuen Wo Road Sports Centre'],
  '000956': ['柯士甸道西、西九文化區', 'Austin Road West, West Kowloon Cultural District'],
  '000972': ['輕鐵洪水橋站、溱林、蔚林', 'LR Hung Shui Kiu Stop, The Woodsville, The Woodside'],
  '000981': ['翠怡花園、太和邨', 'Greenery Plaza, Tai Wo Estate'],
  '001004': ['北街、堅尼地城站', 'North Street, Kennedy Town Station'],
  '001005': ['聯邦新樓、堅尼地城站', 'Luen Bong Apartment, Kennedy Town Station'],
  '001006': ['英皇書院、香港大學東閘', 'King\'s College, HKU East Gate'],
  '001008': ['東邊街、西營盤站', 'Eastern Street, Sai Ying Pun Station'],
  '001009': ['高街、戴麟趾康復中心', 'High Street, David Trench Rehabilitation Centre'],
  '001011': ['豫苑、戴麟趾康復中心', 'Euston Court, David Trench Rehabilitation Centre'],
  '001013': ['東邊街、西營盤站', 'Eastern Street, Sai Ying Pun Station'],
  '001015': ['樓梯街、香港醫學博物館', 'Ladder Street, Hong Kong Museum of Medical Sciences'],
  '001019': ['孫中山紀念館、天主教聖母無原罪主教座堂、清真寺、堅道', 'Dr Sun Yat-sen Museum, The HK Catholic Cathedral of Immaculate Conception, Jamia Mosque, Caine Road'],
  '001020': ['樓梯街、香港醫學博物館', 'Ladder Street, Hong Kong Museum of Medical Sciences'],
  '001021': ['西摩道、香港醫學博物館', 'Seymour Road, HK Museum of Medical Sciences'],
  '001025': ['皇后像廣場、和平紀念碑、大會堂、展城館、中環站', 'Statue Square, The Cenotaph, City Hall, City Gallery, Central Station'],
  '001026': ['中環碼頭－長洲及南丫島渡輪、天星小輪、維多利亞港', 'Central Ferry – Cheung Chau & Lamma Island Ferry, Star Ferry, Victoria Harbour'],
  '001028': ['港澳碼頭、西港城、上環站', 'Macao Ferry, Western Market, Sheung Wan Station'],
  '001029': ['海港政府大樓、四季酒店', 'Harbour Building, Four Seasons Hotel'],
  '001030': ['怡和大廈、中環站、香港站', 'Jardine House, Central Station, Hong Kong Station'],
  '001032': ['中環（交易廣場）、香港站', 'Central (Exchange Square), Hong Kong Station'],
  '001033': ['皇后像廣場、和平紀念碑、大會堂、展城館、中環站', 'Statue Square, The Cenotaph, City Hall, City Gallery, Central Station'],
  '001034': ['砵典乍街、中環站', 'Pottinger Street, Central Station'],
  '001040': ['西港城、港澳碼頭', 'Western Market, Macau Ferry'],
  '001041': ['香港公園、香港壁球中心、茶具文物館', 'Hong Kong Park, Hong Kong Squash Centre, Flagstaff House Museum of Tea Ware'],
  '001044': ['林士街、上環站', 'Rumsey Street, Sheung Wan Station'],
  '001046': ['中環街市、中環至半山自動扶梯', 'Central Market, Central - Mid-Levels Escalators'],
  '001047': ['德忌利士街、中環站、香港站', 'Douglas Street, Central Station, Hong Kong Station'],
  '001048': ['德忌利士街、中環站、香港站', 'Douglas Street, Central Station, Hong Kong Station'],
  '001049': ['德忌利士街、中環站、香港站', 'Douglas Street, Central Station, Hong Kong Station'],
  '001051': ['皇后像廣場、中環站', 'Statue Square, Central Station'],
  '001053': ['滙豐總行大廈、中環站', 'HSBC Main Building, Central Station'],
  '001054': ['置地廣場、中環站', 'The Landmark, Central Station'],
  '001056': ['中環街市、中環至半山自動扶梯', 'Central Market, Central - Mid-Levels Escalators'],
  '001060': ['山道、均益大廈第一期', 'Hill Road, Kwan Yick Building Phase 1'],
  '001061': ['嘉安街、香港今旅', 'Ka On Street, Hotel Jen Hong Kong'],
  '001062': ['西區警署、瑧璈', 'Western Police Station, Bohemian House'],
  '001063': ['正街、瑧蓺', 'Centre Street, Artisan House'],
  '001064': ['東邊街、西營盤站', 'Eastern Street, Sai Ying Pun Station'],
  '001068': ['正街、瑧蓺', 'Centre Street, Artisan House'],
  '001069': ['水街、瑧璈', 'Water Street, Bohemian House'],
  '001070': ['山道、均益大廈第一期', 'Hill Road, Kwan Yick Building Phase 1'],
  '001075': ['大館、孫中山史蹟徑、半山扶手電梯', 'Tai Kwun, Sun Yat Sen Historical Trail, Mid-Levels Escalator'],
  '001076': ['歷山大廈、中環站', 'Alexandra House, Central Station'],
  '001083': ['堅尼地城游泳池、寶翠園', 'Kennedy Town Swimming Pool, The Belcher\'s'],
  '001085': ['女青年會、聖約翰救護機構', 'YWCA, St. John Ambulance'],
  '001096': ['山頂、獅子亭、盧吉道、山頂廣場', 'The Peak, Lions Pavilion, Lugard Road, Peak Galleria'],
  '001097': ['灣仔峽道、警隊博物館', 'Wan Chai Gap Road, Police Museum'],
  '001106': ['畢打街、置地廣場、中環站', 'Pedder Street, The Landmark, Central Station'],
  '001107': ['中區政府碼頭、港澳碼頭、信德中心', 'Central Government Pier, Macau Ferry, Shun Tak Centre'],
  '001112': ['何東夫人堂、寶翠園', 'Lady Ho Tung Hall, The Belcher\'s'],
  '001113': ['香港大學百周年校園、香港大學站', 'HKU Centennial Campus, HKU Station'],
  '001117': ['何東夫人堂、寶翠園', 'Lady Ho Tung Hall, The Belcher\'s'],
  '001129': ['東邊街、西營盤站', 'Eastern Street, Sai Ying Pun Station'],
  '001132': ['朝光街、香港萬怡酒店、華大盛品酒店、華麗都會酒店', 'Chiu Kwong Street, Courtyard by Marriott Hong Kong, Best Western Plus Hotel Hong Kong, Grand City Hotel Hong Kong'],
  '001133': ['石塘咀市政大廈、香港大學站', 'Shek Tong Tsui Complex, HKU Station'],
  '001136': ['金鐘－金鐘花園、太古廣場', 'Admiralty - Admiralty Garden, Pacific Place'],
  '001137': ['金鐘－統一中心、太古廣場', 'Admiralty - United Centre, Pacific Place'],
  '001138': ['金鐘－港鐵 D 出口、太古廣場', 'Admiralty - MTR Exit D, Pacific Place'],
  '001139': ['金鐘－港鐵 B 出口', 'Admiralty - MTR Exit B'],
  '001140': ['金鐘－太古廣場', 'Admiralty - Pacific Place'],
  '001141': ['金鐘－高等法院、太古廣場', 'Admiralty - High Court, Pacific Place'],
  '001143': ['國際金融中心二期、香港站', 'Two International Finance Centre, Hong Kong Station'],
  '001144': ['國際金融中心二期、香港站', 'Two International Finance Centre, Hong Kong Station'],
  '001151': ['金鐘－樂禮街', 'Admiralty - Rodney Street'],
  '001157': ['金鐘－添馬街', 'Admiralty - Tamar Street'],
  '001159': ['摩星嶺徑、芝加哥大學香港校園', 'Mount Davis Path, The University of Chicago Hong Kong Campus'],
  '001160': ['明愛賽馬會宿舍、慈星閣仁愛服務中心', 'Caritas Jockey Club Hostel, Chee Sing Kok Social Centre of the Humanity Life'],
  '001161': ['港島西廢物轉運站、西環鐘聲泳棚', 'Island West Transfer Station, Sai Wan Swimming Shed'],
  '001166': ['港島西廢物轉運站、西環鐘聲泳棚', 'Island West Transfer Station, Sai Wan Swimming Shed'],
  '001167': ['明愛賽馬會宿舍、慈星閣仁愛服務中心', 'Caritas Jockey Club Hostel, Chee Sing Kok Social Centre of the Humanity Life'],
  '001168': ['摩星嶺徑、芝加哥大學香港校園', 'Mount Davis Path, The University of Chicago Hong Kong Campus'],
  '001169': ['金鐘－添馬街', 'Admiralty - Tamar Street'],
  '001172': ['香港空運貨站 (超級一號貨站)、國泰航空貨運站', 'HACTL, Cathay Pacific Cargo Terminal'],
  '001173': ['恒生銀行總行大廈、中環街市', 'Hang Seng Bank Headquarters, Central Market'],
  '001174': ['金鐘－力寶中心、太古廣場', 'Admiralty - Lippo Centre, Pacific Place'],
  '001175': ['急庇利街、上環站', 'Cleverly Street, Sheung Wan Station'],
  '001176': ['國際金融中心商場、香港站', 'IFC Mall, Hong Kong Station'],
  '001178': ['香港站、國際金融中心', 'Hong Kong Station, International Finance Centre'],
  '001180': ['郵政總局、怡和大廈', 'General Post Office, Jardine House'],
  '001183': ['西祥街、堅尼地城游泳池、寶翠園', 'Sai Cheung Street, Kennedy Town Swimming Pool, The Belchers'],
  '001184': ['中環街市、中環至半山自動扶梯', 'Central Market, Central - Mid-Levels Escalators'],
  '001187': ['永安中心、上環站', 'Wing On Centre, Sheung Wan Station'],
  '001188': ['香港潮商學校、香港大學', 'Chiu Sheung School Hong Kong, The University of Hong Kong'],
  '001190': ['水街、瑧璈', 'Water Street, Bohemian House'],
  '001191': ['高樂花園、港島太平洋酒店', 'Connaught Garden, Island Pacific Hotel'],
  '001194': ['中環碼頭－長洲及南丫島渡輪、天星小輪、維多利亞港', 'Central Ferry – Cheung Chau & Lamma Island Ferry, Star Ferry, Victoria Harbour'],
  '001195': ['中環碼頭－長洲及南丫島渡輪、天星小輪、維多利亞港', 'Central Ferry – Cheung Chau & Lamma Island Ferry, Star Ferry, Victoria Harbour'],
  '001210': ['豪景、天寶大廈', 'Ho King View, Tempo Court'],
  '001211': ['賽西湖大廈、香港樹仁大學', 'Braemar Hill Mansions, Hong Kong Shue Yan University'],
  '001213': ['維多利亞公園、香港中央圖書館', 'Victoria Park, Hong Kong Central Library'],
  '001214': ['皇仁書院、維多利亞公園、火龍徑', 'Queen\'s College, Victoria Park, Fire Dragon Path'],
  '001215': ['香港中央圖書館、維多利亞公園', 'Hong Kong Central Library, Victoria Park'],
  '001216': ['阿公岩道、香島', 'A Kung Ngam Road, Island Garden'],
  '001219': ['東區醫院、興民邨、樂翠臺', 'Eastern Hospital, Hing Man Estate, Neptune Terrace'],
  '001221': ['康民街、興華（二）邨', 'Hong Man Street, Hing Wah (II) Estate'],
  '001222': ['怡泰街、永利中心', 'Yee Tai Street, Winner Centre'],
  '001225': ['常安街、富城閣、蝶翠苑', 'Sheung On Street, Fu Shing Court, Dip Tsui Court'],
  '001231': ['山翠苑、東區醫院', 'Shan Tsui Court, Eastern Hospital'],
  '001233': ['阿公岩道、香島', 'A Kung Ngam Road, Island Garden'],
  '001243': ['電氣道街市、炮台山站', 'Electric Road Market, Fortress Hill Station'],
  '001244': ['城市花園、城市花園酒店', 'City Garden, City Garden Hotel'],
  '001248': ['歌頓道、銅鑼灣皇悅酒店', 'Gordon Road, Empire Hotel Causeway Bay'],
  '001249': ['北角碼頭、香港維港凱悅尚萃酒店、宜必思香港北角酒店', 'North Point Ferry Pier, Hyatt Centric Victoria Harbour Hong Kong, Ibis Hong Kong North Point'],
  '001251': ['興發街、銅鑼灣如心酒店', 'Hing Fat Street, Nina Hotel Causeway Bay'],
  '001254': ['北角道、和富中心', 'North Point Road, Provident Centre'],
  '001255': ['渣華道市政大廈、北角站', 'Java Road Complex, North Point Station'],
  '001256': ['琴行街、北角碼頭、北角站', 'Kam Hong Street, North Point Ferry Pier, North Point Station'],
  '001258': ['北角消防局、北角政府合署', 'North Point Fire Station, North Point Government Offices'],
  '001259': ['銀幕街、天后站', 'Ngan Mok Street, Tin Hau Station'],
  '001260': ['七海商業中心、炮台山站', '7 Seas Shopping Centre, Fortress Hill Station'],
  '001263': ['書局街、北角站', 'Shu Kuk Street, North Point Station'],
  '001266': ['模範邨、北角海逸酒店', 'Model Housing Estate, Harbour Plaza North Point'],
  '001267': ['北角官立小學、鰂魚涌站', 'North Point Government Primary School, Quarry Bay Station'],
  '001268': ['新威園、太古坊', 'Sunway Gardens, Taikoo Place'],
  '001270': ['太古城中心、康山花園', 'Cityplaza, Kornhill Gardens'],
  '001275': ['模範邨、北角海逸酒店', 'Model Housing Estate, Harbour Plaza North Point'],
  '001279': ['琴行街、北角站', 'Kam Hong Street, North Point Station'],
  '001287': ['康怡廣場、太古站', 'Kornhill Plaza, Tai Koo Station'],
  '001288': ['康怡廣場、太古站', 'Kornhill Plaza, Tai Koo Station'],
  '001293': ['鯉景灣、嘉亨灣、東區法院大樓', 'Lei King Wan, Grand Promenade, Eastern Law Court Building'],
  '001296': ['太安樓、西灣河站', 'Tai On Building, Sai Wan Ho Station'],
  '001303': ['西灣河文娛中心、西灣河站', 'Sai Wan Ho Civic Centre, Sai Wan Ho Station'],
  '001308': ['城巴柴灣車廠、香港高等教育科技學院（柴灣校園）', 'Citybus Chai Wan Garage, THEi (Chai Wan Campus)'],
  '001309': ['香港專業教育學院（柴灣分校）、香港高等教育科技學院（柴灣校園）', 'HKIVE (Chai Wan), THEi (Chai Wan Campus)'],
  '001310': ['馬寶道、北角站', 'Marble Road, North Point Station'],
  '001316': ['西灣河站、西灣河文娛中心', 'Sai Wan Ho Station, Sai Wan Ho Civic Centre'],
  '001324': ['百福道、寶馬山花園', 'Pak Fuk Road, Pacific Palisades'],
  '001331': ['百福道、寶馬山花園', 'Pak Fuk Road, Pacific Palisades'],
  '001332': ['書局街、北角站', 'Shu Kuk Street, North Point Station'],
  '001333': ['皇仁書院、大坑蓮花宮', 'Queen\'s College, Tai Hang Lin Fa Kung'],
  '001334': ['中華游樂會、浣紗街、大坑火龍文化館', 'Chinese Recreation Club, Wun Sha Street, Tai Hang Fire Dragon Heritage Centre'],
  '001335': ['銅鑼灣避風塘、維多利亞公園', 'Causeway Bay Typhoon Shelter, Victoria Park'],
  '001338': ['青年廣場、Y旅舍、環翠邨', 'Youth Square, Y Loft, Wan Tsui Estate'],
  '001343': ['柴灣工業城、翠灣邨、漁灣邨、香港高等教育科技學院（柴灣校園）', 'Chai Wan Industrial City, Tsui Wan Estate, Yue Wan Estate, THEi (Chai Wan Campus)'],
  '001347': ['北角官立小學 (雲景道)', 'North Point Government Primary School (Cloud View Road)'],
  '001348': ['北角官立小學 (雲景道)', 'North Point Government Primary School (Cloud View Road)'],
  '001362': ['富欣花園、小西灣邨', 'Harmony Garden, Siu Sai Wan Estate'],
  '001365': ['新威園、太古坊', 'Sunway Gardens, Taikoo Place'],
  '001369': ['富怡花園、佳翠苑', 'Cheerful Garden, Kai Tsui Court'],
  '001371': ['張振興伉儷書院、柴灣公園', 'Chong Gene Hang College, Chai Wan Park'],
  '001372': ['張振興伉儷書院、柴灣公園', 'Chong Gene Hang College, Chai Wan Park'],
  '001373': ['琴行街、北角站', 'Kam Hong Street, North Point Station'],
  '001394': ['小西灣運動場、藍灣半島', 'Siu Sai Wan Sports Ground, Island Resort'],
  '001395': ['通菜街、先達廣場、SKYPARK、旺角站', 'Tung Choi Street, Sincere Podium, SKYPARK, Mong Kok Station'],
  '001396': ['油尖旺地區康健中心、旺角街市、香港康得思酒店、朗豪坊', 'Yau Tsim Mong District Health Centre, Mong Kok Market, Cordis Hong Kong, Langham Place'],
  '001397': ['崇潔街、九龍城政府合署', 'Sung Kit Street, Kowloon City Government Offices'],
  '001398': ['中港城、戲曲中心', 'China Hong Kong City, Xiqu Centre'],
  '001400': ['匯翔道、柯士甸站', 'Wui Cheung Road, Austin Station'],
  '001401': ['新港中心、海港城、港威酒店', 'Silvercord, Harbour City, Gateway Hotel'],
  '001402': ['北京道、天星碼頭、維多利亞港、海港城、1881', 'Peking Road, Star Ferry, Victoria Harbour, Harbour City, 1881 Heritage'],
  '001403': ['戲曲中心、香港皇家太平洋酒店', 'Xiqu Centre, Royal Pacific Hotel'],
  '001416': ['麼地道、尖沙咀凱悅酒店、九龍香格里拉酒店、帝苑酒店、富豪九龍酒店、粵海酒店、隆堡麗景酒店、憙酒店 (香港)', 'Mody Road, Hyatt Regency Hong Kong Tsim Sha Tsui, Kowloon Shangri-La, The Royal Garden, Regal Kowloon Hotel, Guangdong Hotel, Hotel Panorama By Rhombus, Xi Hotel'],
  '001417': ['加連威老道、百樂酒店、最佳盛品酒店尖沙咀、海景嘉福洲際酒店、千禧新世界香港酒店', 'Granville Road, Park Hotel, Best Western Plus Hotel Kowloon, InterContinental Grand Stanford Hong Kong, New World Millennium Hong Kong Hotel'],
  '001418': ['香港科學館、仕德福山景酒店、尖沙咀皇悅酒店、唯港薈', 'Hong Kong Science Museum, Stanford Hillview Hotel, Empire Hotel Kowloon - Tsim Sha Tsui, Hotel ICON'],
  '001419': ['香港科學館、仕德福山景酒店、尖沙咀皇悅酒店、唯港薈', 'Hong Kong Science Museum, Stanford Hillview Hotel, Empire Hotel Kowloon - Tsim Sha Tsui, Hotel ICON'],
  '001420': ['麼地道、尖沙咀凱悅酒店、九龍香格里拉酒店、帝苑酒店、富豪九龍酒店、粵海酒店、隆堡麗景酒店、憙酒店 (香港)', 'Mody Road, Hyatt Regency Hong Kong Tsim Sha Tsui, Kowloon Shangri-La, The Royal Garden, Regal Kowloon Hotel, Guangdong Hotel, Hotel Panorama By Rhombus, Xi Hotel'],
  '001423': ['銘基書院、奧海城3期', 'Ming Kei College, Olympian City 3'],
  '001424': ['銘基書院、奧海城3期', 'Ming Kei College, Olympian City 3'],
  '001428': ['北河街、深水埗站', 'Pei Ho Street, Sham Shui Po Station'],
  '001429': ['北河街、深水埗站', 'Pei Ho Street, Sham Shui Po Station'],
  '001433': ['荔枝角站、長沙灣廣場', 'Lai Chi Kok Station, Cheung Sha Wan Plaza'],
  '001434': ['長荔街、荔枝角站', 'Cheung Lai Street, Lai Chi Kok Station'],
  '001436': ['荔枝角站、長沙灣廣場', 'Lai Chi Kok Station, Cheung Sha Wan Plaza'],
  '001438': ['長沙灣站、元州邨', 'Cheung Sha Wan Station, Un Chau Estate'],
  '001443': ['欽州街、長沙灣政府合署', 'Yen Chow Street, Cheung Sha Wan Government Offices'],
  '001444': ['北河街、深水埗站', 'Pei Ho Street, Sham Shui Po Station'],
  '001452': ['四美街、啟翔苑、采頤花園', 'Sze Mei Street, Kai Cheung Court, Rhythm Garden'],
  '001453': ['大有街、啟鑽苑', 'Tai Yau Street, Kai Chuen Court'],
  '001474': ['裕民坊、觀塘站', 'Yue Man Square (YM2), Kwun Tong Station'],
  '001475': ['海底隧道巴士轉乘站、香港理工大學、紅磡站', 'Cross Harbour Tunnel Bus-Bus Interchange, The Hong Kong Polytechnic University, Hung Hom Station'],
  '001476': ['海底隧道巴士轉乘站、香港理工大學、紅磡站', 'Cross Harbour Tunnel Bus-Bus Interchange, The Hong Kong Polytechnic University, Hung Hom Station'],
  '001477': ['德民街、黃埔新邨', 'Tak Man Street, Whampoa Estate'],
  '001481': ['廟街、廟街夜市', 'Temple Street, Temple Street Night Market'],
  '001482': ['炮台街、玉器市場及玉器街', 'Battery Street, Jade Street & Jade Market'],
  '001483': ['上海街、廟街', 'Shanghai Street, Temple Street'],
  '001484': ['志和街、佐敦站', 'Chi Wo Street, Jordan Station'],
  '001494': ['駿業里、觀塘市中心、apm', 'Tsun Yip Lane, Kwun Tong Town Centre, apm'],
  '001495': ['創紀之城、牛頭角站', 'Millennium City, Ngau Tau Kok Station'],
  '001496': ['定富街、工業家酒店、IW酒店', 'Ting Fu Street, ind Hotel, IW Hotel'],
  '001497': ['定富街、工業家酒店、IW酒店', 'Ting Fu Street, ind Hotel, IW Hotel'],
  '001500': ['九龍灣站、德福花園、東九文化中心', 'Kowloon Bay Station, Telford Gardens, East Kowloon Cultural Centre'],
  '001501': ['啟泰苑、啟業邨', 'Kai Tai Court, Kai Yip Estate'],
  '001505': ['九龍灣站、德福花園、東九文化中心', 'Kowloon Bay Station, Telford Gardens, East Kowloon Cultural Centre'],
  '001507': ['定富街、工業家酒店、IW酒店', 'Ting Fu Street, ind Hotel, IW Hotel'],
  '001508': ['牛頭角站、創紀之城', 'Ngau Tau Kok Station, Millennium City'],
  '001509': ['觀塘市中心、apm', 'Kwun Tong Town Centre, apm'],
  '001515': ['旺角維景酒店、鴉蘭街', 'Metropark Hotel Mongkok, Arran Street'],
  '001523': ['黃大仙站、黃大仙中心', 'Wong Tai Sin Station, Temple Mall'],
  '001526': ['鑽石山站、荷里活廣場', 'Diamond Hill Station, Plaza Hollywood'],
  '001534': ['落山道、土瓜灣街市', 'Lok Shan Road, To Kwa Wan Market'],
  '001536': ['馬頭圍邨洋葵樓、8度海逸酒店', 'Geranium House, Ma Tau Wai Estate, Harbour Plaza 8 Degrees'],
  '001537': ['海底隧道巴士轉乘站、香港理工大學、紅磡站', 'Cross Harbour Tunnel Bus-Bus Interchange, The Hong Kong Polytechnic University, Hung Hom Station'],
  '001541': ['九龍酒店、中間道', 'Kowloon Hotel, Middle Road'],
  '001542': ['海防道、名鑄', 'Haiphong Road, The Masterpiece'],
  '001543': ['金巴利道、美麗華酒店、君怡酒店、帝樂文娜公館、尖沙咀皇悦卓越酒店', 'Kimberley Road, The Mira Hong Kong, The Kimberley Hotel, The Luxe Manor, Empire Prestige Tsim Sha Tsui'],
  '001545': ['佐敦站、寶靈街', 'Jordan Station, Bowring Street'],
  '001546': ['南京街、佐敦站', 'Nanking Street, Jordan Station'],
  '001548': ['登打士街、周大福商業中心、信和中心', 'Dundas Street, Chow Tai Fook Centre, Sino Centre'],
  '001549': ['碧街、油麻地站', 'Pitt Street, Yau Ma Tei Station'],
  '001551': ['長沙街、信和中心', 'Changsha Street, Sino Centre'],
  '001552': ['山東街、雅蘭中心、朗豪坊、旺角站', 'Shantung Street, Grand Plaza, Langham Place, Mong Kok Station'],
  '001553': ['銀行中心、奶路臣街、旺角站', 'Bank Centre, Nelson Street, Mong Kok Station'],
  '001554': ['弼街、始創中心', 'Bute Street, Pioneer Centre'],
  '001557': ['聯合廣場、水渠道', 'Allied Plaza, Nullah Road'],
  '001558': ['旺角中心、旺角站', 'Argyle Centre, Mong Kok Station'],
  '001559': ['銀行中心、奶路臣街、旺角站', 'Bank Centre, Nelson Street, Mong Kok Station'],
  '001560': ['山東街、雅蘭中心、朗豪坊、旺角站', 'Shantung Street, Grand Plaza, Langham Place, Mong Kok Station'],
  '001561': ['信和中心、豉油街', 'Sino Centre, Soy Street'],
  '001562': ['登打士街、周大福商業中心、信和中心', 'Dundas Street, Chow Tai Fook Centre, Sino Centre'],
  '001563': ['碧街、油麻地站', 'Pitt Street, Yau Ma Tei Station'],
  '001564': ['文明里、城景國際、卜維廉賓館、明愛白英奇賓館、香港海景絲麗酒店、九龍王子酒店、旭逸酒店．旺角、油麻地站', 'Man Ming Lane, The Cityview, Booth Lodge, Caritas Bianchi Lodge, Silka Hotel, Kings de Nathan, Hotel Ease Mong Kok, Yau Ma Tei Station'],
  '001565': ['永星里、油麻地站', 'Wing Sing Lane, Yau Ma Tei Station'],
  '001567': ['彌敦酒店、西貢街', 'Nathan Hotel, Saigon Street'],
  '001568': ['恆豐中心、德成街、佐敦站', 'Prudential Centre, Tak Shing Street, Jordan Station'],
  '001569': ['金巴利道、美麗華酒店、君怡酒店、帝樂文娜公館、尖沙咀皇悦卓越酒店', 'Kimberley Road, The Mira Hong Kong, The Kimberley Hotel, The Luxe Manor, Empire Prestige Tsim Sha Tsui'],
  '001570': ['金馬倫道、尖沙咀站', 'Cameron Road, Tsim Sha Tsui Station'],
  '001571': ['九龍酒店、中間道', 'Kowloon Hotel, Middle Road'],
  '001573': ['譽．港灣、Mikiki、AIRSIDE、工業貿易大樓', 'The Latitude, Mikiki, AIRSIDE, Trade and Industry Tower'],
  '001574': ['采頤花園、景泰苑', 'Rhythm Garden, King Tai Court'],
  '001575': ['采頤花園、景泰苑', 'Rhythm Garden, King Tai Court'],
  '001576': ['譽．港灣、Mikiki、AIRSIDE、工業貿易大樓', 'The Latitude, Mikiki, AIRSIDE, Trade and Industry Tower'],
  '001578': ['嘉輝台、愛民邨', 'Greenfield Terrace, Oi Man Estate'],
  '001579': ['醫療輔助隊總部、香港都會大學', 'Auxiliary Medical Services Headquarters, Hong Kong Metropolitan University'],
  '001580': ['醫療輔助隊總部、香港都會大學', 'Auxiliary Medical Services Headquarters, Hong Kong Metropolitan University'],
  '001585': ['快富街、朗豪坊', 'Fife Street, Langham Place'],
  '001586': ['柯士甸站、高鐵西九龍站', 'Austin Station, HSR West Kowloon Station'],
  '001587': ['尖東站、K11人文購物藝術館', 'East Tsim Sha Tsui Station, K11 MUSEA'],
  '001588': ['尖沙咀（天星碼頭）、海港城', 'Tsim Sha Tsui (Star Ferry), Harbour City'],
  '001589': ['尖東站、K11人文購物藝術館', 'East Tsim Sha Tsui Station, K11 MUSEA'],
  '001593': ['九龍灣（企業廣場）、Megabox', 'Kowloon Bay (Enterprise Square), Megabox'],
  '001598': ['藍田 (北)、藍田綜合大樓、德田廣場', 'Lam Tin (North), Lam Tin Complex, Tak Tin Plaza'],
  '001601': ['麗閣邨、長沙灣邨', 'Lai Kok Estate, Cheung Sha Wan Estate'],
  '001602': ['長沙灣站、元州邨', 'Cheung Sha Wan Station, Un Chau Estate'],
  '001603': ['維港灣、奧海城1期', 'Island Harbourview, Olympian City 1'],
  '001606': ['偉樂街、麗港城、茶果嶺海濱公園', 'Wai Lok Street, Laguna City, Cha Kwo Ling Promenade'],
  '001610': ['盛緻苑、麗晶花園第 8 座、啟晴邨', 'Shing Chi Court, Block 8 Richland Gardens, Kai Ching Estate'],
  '001613': ['麗晶商場、德朗邨', 'Richland Gardens Shopping Centre, Tak Long Estate'],
  '001614': ['麗晶商場、德朗邨', 'Richland Gardens Shopping Centre, Tak Long Estate'],
  '001620': ['九龍塘官立小學、九龍塘站', 'Kowloon Tong Government Primary School, Kowloon Tong Station'],
  '001623': ['九龍塘官立小學、九龍塘站', 'Kowloon Tong Government Primary School, Kowloon Tong Station'],
  '001628': ['西區海底隧道巴士轉乘站、圓方、九龍站', 'Western Harbour Crossing Bus-Bus Interchange, Elements, Kowloon Station'],
  '001629': ['西區海底隧道巴士轉乘站、圓方、九龍站', 'Western Harbour Crossing Bus-Bus Interchange, Elements, Kowloon Station'],
  '001635': ['深水埗（欽州街）、西九龍中心', 'Sham Shui Po (Yen Chow Street), Dragon Centre'],
  '001638': ['基隆街、西九龍中心', 'Ki Lung Street, Dragon Centre'],
  '001641': ['啟田邨啟旺樓、康逸苑', 'Kai Wong House, Kai Tin Estate, Hong Yat Court'],
  '001642': ['天主教伍華中學、譽港灣', 'Ng Wah Catholic Secondary School, The Latitude'],
  '001645': ['麗晶花園第18座、啟業邨', 'Block 18 Richland Gardens, Kai Yip Estate'],
  '001647': ['裕民坊、apm、觀塘站', 'Yue Man Square, apm, Kwun Tong Station'],
  '001649': ['MegaBox、零碳天地', 'MegaBox, Zero Carbon Park'],
  '001654': ['坪石邨、彩虹站', 'Ping Shek Estate, Choi Hung Station'],
  '001655': ['企業廣場、零碳天地', 'Enterprise Square, Zero Carbon Park'],
  '001670': ['觀塘警署、香港觀塘帝盛酒店', 'Kwun Tong Police Station, Dorsett Kwun Tong, Hong Kong'],
  '001671': ['景林邨景榕樓、將軍澳游泳池、頌明苑', 'King Yung House King Lam Estate, Tseung Kwan O Swimming Pool, Chung Ming Court'],
  '001680': ['英明苑、寶林邨', 'Ying Ming Court, Po Lam Estate'],
  '001687': ['貿易廣場、元州邨', 'Trade Square, Un Chau Estate'],
  '001690': ['黃大仙站、黃大仙中心', 'Wong Tai Sin Station, Temple Mall'],
  '001692': ['奧運站、滙豐中心', 'Olympic Station, HSBC Centre'],
  '001696': ['鑽石山站、荷里活廣場', 'Diamond Hill Station, Plaza Hollywood'],
  '001699': ['四美街、啟翔苑、采頤花園', 'Sze Mei Street, Kai Cheung Court, Rhythm Garden'],
  '001707': ['浪澄灣、維港灣', 'The Long Beach, Island Harbourview'],
  '001710': ['宏景花園、富山邨', 'Grand View Garden, Fu Shan Estate'],
  '001712': ['慈安苑、慈雲山中心', 'Tsz On Court, Tsz Wan Shan Shopping Centre'],
  '001727': ['重華路、東港城', 'Chung Wa Road, East Point City'],
  '001734': ['天馬苑、橫頭磡邨', 'Tin Ma Court, Wang Tau Hom Estate'],
  '001736': ['南豐廣場、培成路、坑口站', 'Nan Fung Plaza, Pui Shing Road, Hang Hau Station'],
  '001738': ['英明苑、寶林邨', 'Ying Ming Court, Po Lam Estate'],
  '001741': ['創紀之城、牛頭角站', 'Millennium City, Ngau Tau Kok Station'],
  '001744': ['順安邨安逸樓、順天邨', 'On Yat House, Shun On Estate, Shun Tin Estate'],
  '001761': ['天馬苑、橫頭磡邨', 'Tin Ma Court, Wang Tau Hom Estate'],
  '001762': ['凱德苑、發祥街西、西九龍法院大樓', 'Hoi Tak Court, Fat Tseung Street West, West Kowloon Law Courts Building'],
  '001764': ['調景嶺站、香港知專設計學院', 'Tiu Keng Leng Station, Hong Kong Design Institute'],
  '001770': ['旺角警署、太子站', 'Mong Kok Police Station, Prince Edward Station'],
  '001774': ['基榮小學、始創中心', 'Kei Wing Primary School, Pioneer Centre'],
  '001775': ['旺角中心、旺角站', 'Argyle Centre, Mong Kok Station'],
  '001777': ['中匯街、君匯港、大同新邨', 'Chung Wui Street, Harbour Green, Cosmopolitan Estates'],
  '001785': ['欣明苑、新都城二期、寶琳站', 'Yan Ming Court, Metro City II, Po Lam Station'],
  '001791': ['油塘中心、鯉魚門邨', 'Yau Tong Centre, Lei Yue Mun Estate'],
  '001792': ['油塘、大本型', 'Yau Tong, Domain'],
  '001801': ['鴉蘭街、太子站', 'Arran Street, Prince Edward Station'],
  '001802': ['欽州街、長沙灣政府合署', 'Yen Chow Street, Cheung Sha Wan Government Offices'],
  '001807': ['民泰街、黃埔花園', 'Man Tai Street, Whampoa Garden'],
  '001812': ['貴州街、偉恒昌新邨', 'Kwei Chow Street, Wyler Garden'],
  '001817': ['九龍中央郵政局、舊油麻地警署、廟街', 'Kowloon Central Post Office, Former Yau Ma Tei Police Station, Temple Street'],
  '001818': ['寶盈花園、怡明邨、將軍澳站', 'Bauhinia Garden, Yee Ming Estate, Tseung Kwan O Station'],
  '001819': ['將軍澳站、天晉', 'Tseung Kwan O Station, The Wings'],
  '001820': ['入境事務處總部、將軍澳中心', 'Immigration Headquarters, Park Central'],
  '001822': ['富康花園、香港單車館、將軍澳運動場、將軍澳廣場', 'Beverly Garden, Hong Kong Velodrome, Tseung Kwan O Sports Ground, Tseung Kwan O Plaza'],
  '001823': ['TKO Spot、尚德', 'TKO Spot, Sheung Tak'],
  '001824': ['將軍澳中心、入境事務處總部', 'Park Central, Immigration Headquarters'],
  '001825': ['將軍澳站、天晉', 'Tseung Kwan O Station, The Wings'],
  '001826': ['將軍澳廣場、君傲灣', 'Tseung Kwan O Plaza, The Grandiose'],
  '001834': ['1號客運大樓（北）', 'Terminal 1 (North)'],
  '001855': ['東堤灣畔、東涌纜車站', 'Tung Chung Crescent, Tung Chung Cable Car Terminal'],
  '001856': ['東涌消防局、東薈城', 'Tung Chung Fire Station, Citygate'],
  '001860': ['東涌站、東涌纜車站', 'Tung Chung Station, Tung Chung Cable Car Terminal'],
  '001863': ['香港空運貨站 (超級一號貨站)、國泰航空貨運站', 'HACTL, Cathay Pacific Cargo Terminal'],
  '001868': ['民航處總部、國泰坊、中航大廈', 'CAD Headquarters, Cathay House, CNAC House'],
  '001869': ['東堤灣畔、東涌纜車站', 'Tung Chung Crescent, Tung Chung Cable Car Terminal'],
  '001874': ['逸東邨美逸樓、裕泰苑、北大嶼山醫院', 'Mei Yat House Yat Tung Estate, Yu Tai Court, North Lantau Hospital'],
  '001876': ['水藍．天岸、海堤灣畔、諾富特東薈城酒店', 'Le Bleu Deux, Seaview Crescent, Novotel Citygate Hong Kong'],
  '001877': ['水藍．天岸、海堤灣畔、諾富特東薈城酒店', 'Le Bleu Deux, Seaview Crescent, Novotel Citygate Hong Kong'],
  '001878': ['藍天海岸、東涌市政大樓', 'Coastal Skyline, Tung Chung Municipal Services Building'],
  '001879': ['東涌市政大樓、文東路體育館、東薈城', 'Tung Chung Municipal Services Building, Man Tung Road Sports Centre, Citygate'],
  '001880': ['映灣園二期、東涌北公園', 'Caribbean Coast Phase 2, Tung Chung North Park'],
  '001883': ['映灣園二期、東涌北公園', 'Caribbean Coast Phase 2, Tung Chung North Park'],
  '001888': ['咖啡灣、青山灣入境事務中心', 'Cafeteria Beach, Castle Peak Bay Immigration Centre'],
  '001889': ['黃金泳灘、黃金海岸酒店', 'Golden Beach, Gold Coast Hotel'],
  '001890': ['香港黃金海岸、愛琴海岸、掃管笏', 'Hong Kong Gold Coast, Aegean Coast, So Kwun Wat'],
  '001900': ['龍珠島、香港黃金海岸二期', 'Pearl Island, Hong Kong Gold Coast (Phase 2)'],
  '001901': ['黃金泳灘、黃金海岸酒店', 'Golden Beach, Gold Coast Hotel'],
  '001902': ['香港黃金海岸、愛琴海岸、掃管笏', 'Hong Kong Gold Coast, Aegean Coast, So Kwun Wat'],
  '001903': ['咖啡灣、青山灣入境事務中心', 'Cafeteria Beach, Castle Peak Bay Immigration Centre'],
  '001910': ['秦石邨、香港文化博物館、車公廟站', 'Chun Shek Estate, Hong Kong Heritage Museum, Che Kung Temple Station'],
  '001911': ['秦石邨、香港文化博物館、車公廟站', 'Chun Shek Estate, Hong Kong Heritage Museum, Che Kung Temple Station'],
  '001914': ['馬鞍山運動場、曾璧山(崇蘭)中學', 'Ma On Shan Sports Ground, Tsang Pik Shan (Sung Lan) Secondary School'],
  '001916': ['耀安邨、恒安邨', 'Yiu On Estate, Heng On Estate'],
  '001917': ['馬鞍山運動場、曾璧山(崇蘭)中學', 'Ma On Shan Sports Ground, Tsang Pik Shan (Sung Lan) Secondary School'],
  '001921': ['智芳街、葵芳邨', 'Che Fong Street, Kwai Fong Estate'],
  '001922': ['老鼠洲兒童遊樂場、恒福花園、兆麟苑', 'Mouse Island Children\'s Playground, Hanford Garden, Siu Lun Court'],
  '001923': ['恒福花園、三聖邨、兆麟苑', 'Hanford Garden, Sam Shing Estate, Siu Lun Court'],
  '001925': ['新翠邨、大圍站', 'Sun Chui Estate, Tai Wai Station'],
  '001926': ['新翠邨、大圍站', 'Sun Chui Estate, Tai Wai Station'],
  '001929': ['葵涌廣場、新都會廣場、葵芳站', 'Kwai Chung Plaza, Metroplaza, Kwai Fong Station'],
  '001936': ['新屯門中心、屯門游泳池、輕鐵車廠站 L', 'Sun Tuen Mun Centre, Tuen Mun Swimming Pool, Light Rail Depot Stop L'],
  '001938': ['新屯門中心、屯門游泳池、輕鐵車廠站 L', 'Sun Tuen Mun Centre, Tuen Mun Swimming Pool, Light Rail Depot Stop L'],
  '001940': ['沙田第一城第11座、第一城中心', 'Block 11 City One Shatin, City One Plaza'],
  '001942': ['沙田第一城第11座、第一城中心', 'Block 11 City One Shatin, City One Plaza'],
  '001946': ['天水圍站 - 天盛苑、屏欣苑', 'Tin Shui Wai Station - Tin Shing Court, Ping Yan Court'],
  '001947': ['天水圍站 - 天盛苑、屏欣苑', 'Tin Shui Wai Station - Tin Shing Court, Ping Yan Court'],
  '001951': ['上水、上水廣場', 'Sheung Shui, Landmark North'],
  '001952': ['沙角邨、博康邨、沙田圍站', 'Sha Kok Estate, Pok Hong Estate, Sha Tin Wai Station'],
  '001953': ['博康邨、沙田圍站', 'Pok Hong Estate, Sha Tin Wai Station'],
  '001955': ['尚翠苑、名逸居', 'Sheung Chui Court, New Haven'],
  '001957': ['戴麟趾夫人診療所、荃新天地', 'Lady Trench Polyclinic, Citywalk'],
  '001958': ['戴麟趾夫人診療所、荃新天地', 'Lady Trench Polyclinic, Citywalk'],
  '001961': ['沙田站、新城市廣場', 'Sha Tin Station, New Town Plaza'],
  '001985': ['大老山隧道巴士轉乘站、香港恒生大學', 'Tate\'s Cairn Tunnel Bus-Bus Interchange, The Hang Seng University of Hong Kong'],
  '001986': ['大老山隧道巴士轉乘站、香港恒生大學', 'Tate\'s Cairn Tunnel Bus-Bus Interchange, The Hang Seng University of Hong Kong'],
  '001987': ['荃富街、尚文苑', 'Tsuen Fu Street, Sheung Man Court'],
  '001988': ['嘉湖山莊麗湖居、美湖居', 'Lynwood Court, Maywood Court, Kingswood Villas'],
  '001996': ['輕鐵翠湖站、天頌苑、嘉湖山莊翠湖居', 'LR Chestwood Stop, Tin Chung Court, Kingswood Villas - Chestwood Court'],
  '001997': ['輕鐵翠湖站、天頌苑、嘉湖山莊翠湖居', 'LR Chestwood Stop, Tin Chung Court, Kingswood Villas - Chestwood Court'],
  '002004': ['青華苑、長康邨', 'Ching Wah Court, Cheung Hong Estate'],
  '002007': ['青華苑、長康邨', 'Ching Wah Court, Cheung Hong Estate'],
  '002008': ['蝴蝶邨蝶心樓、美樂花園', 'Tip Sum House Butterfly Estate, Melody Garden'],
  '002009': ['湖景邨湖碧樓、啟豐園', 'Wu Pik House Wu King Estate, Richland Garden'],
  '002010': ['美樂花園、蝴蝶邨', 'Melody Garden, Butterfly Estate'],
  '002032': ['嘉湖山莊景湖居、嘉湖海逸酒店', 'Kenswood Court Kingswood Villas, Harbour Plaza Resort City'],
  '002036': ['輕鐵銀座站、嘉湖海逸酒店', 'LR Ginza Stop, Harbour Plaza Resort City'],
  '002039': ['邁亞美海灣、慧豐園', 'Miami Beach Towers, Marina Garden'],
  '002041': ['恒順園、置樂花園', 'Handsome Court, Chi Lok Fa Yuen'],
  '002046': ['沙田市中心、新城市廣場', 'Shatin Central, New Town Plaza'],
  '002051': ['第一城站、威爾斯親王醫院', 'City One Station, Prince of Wales Hospital'],
  '002058': ['小欖、帝濤灣', 'Siu Lam, Palatial Coast'],
  '002062': ['天頌苑頌棋閣、天悅邨', 'Chung Ki House Tin Chung Court, Tin Yuet Estate'],
  '002063': ['天頌苑頌恩閣、天華邨', 'Chung Yan House Tin Chung Court, Tin Wah Estate'],
  '002089': ['將軍澳醫院、半見村', 'Tseung Kwan O Hospital, Boon Kin Village'],
  '002094': ['大埔仔村、傲瀧', 'Tai Po Tsai Village, Mount Pavilia'],
  '002104': ['北港、獅子會自然教育中心', 'Pak Kong, Lions Nature Education Centre'],
  '002105': ['菠蘿輋、西貢戶外康樂中心', 'Po Lo Che, Sai Kung Outdoor Recreation Centre'],
  '002107': ['西貢大會堂、西貢市中心', 'Sai Kung Town Hall, Sai Kung Town Centre'],
  '002116': ['亞公灣、香港外展訓練學校', 'Ah Kung Wan, Outward Bound Hong Kong'],
  '002128': ['亞公灣、香港外展訓練學校', 'Ah Kung Wan, Outward Bound Hong Kong'],
  '002135': ['西貢大會堂、西貢市中心', 'Sai Kung Town Hall, Sai Kung Town Centre'],
  '002137': ['菠蘿輋、西貢戶外康樂中心', 'Po Lo Che, Sai Kung Outdoor Recreation Centre'],
  '002138': ['北港、獅子會自然教育中心', 'Pak Kong, Lions Nature Education Centre'],
  '002148': ['大埔仔村、傲瀧', 'Tai Po Tsai Village, Mount Pavilia'],
  '002157': ['聖伯多祿堂、香港仔中心', 'St. Peter\'s Church, Aberdeen Centre'],
  '002160': ['逸港居、香港仔網球及壁球中心', 'Ocean Court, Aberdeen Tennis & Squash Centre'],
  '002161': ['香港仔', 'Aberdeen'],
  '002164': ['崇文街、香港仔天后廟', 'Tsung Man Street、Aberdeen Tin Hau Temple'],
  '002165': ['漁光村白沙樓、聖伯多祿中學', 'Pak Sha Lau Yue Kwong Chuen, St. Peter\'s Secondary School'],
  '002168': ['利枝道、鴨脷洲大街', 'Lee Chi Road, Main Street Ap Lei Chau'],
  '002169': ['御庭園、鴨脷洲邨', 'The Oasis, Ap Lei Chau Estate'],
  '002172': ['利枝道、鴨脷洲大街', 'Lee Chi Road, Main Street Ap Lei Chau'],
  '002210': ['利東邨東興樓、鴨脷洲街坊學校、利東站', 'Tung Hing House Lei Tung Estate, Aplichau Kaifong Primary School, Lei Tung Station'],
  '002213': ['香港真光書院、漁安苑', 'Hong Kong True Light College, Yue On Court'],
  '002215': ['洛陽街、香港仔中心', 'Lok Yeung Street, Aberdeen Centre'],
  '002217': ['黃竹坑老人服務綜合大樓、港大同學會書院', 'Wong Chuk Hang Complex for the Elderly, HKUGA College'],
  '002221': ['港大同學會書院、黃竹坑老人服務綜合大樓', 'HKUGA College, Wong Chuk Hang Complex for the Elderly'],
  '002224': ['南朗山道熟食市場、黃竹坑站、THE SOUTHSIDE', 'Nam Long Shan Road Cooked Food Market, Wong Chuk Hang Station, THE SOUTHSIDE'],
  '002225': ['海洋公園、香港海洋公園萬豪酒店', 'Ocean Park, Hong Kong Ocean Park Marriott Hotel'],
  '002226': ['余振強紀念第二中學、薄扶林花園', 'Yu Chun Keung Memorial College No.2, Pokfulam Gardens'],
  '002227': ['薄扶林村、職業訓練局薄扶林大樓', 'Pok Fu Lam Village, VTC Pokfulam Complex'],
  '002232': ['香港華人基督教聯會薄扶林道墳場、啟明寺', 'HKCCCU Pok Fu Lam Road Cemetery, Kai Ming Temple'],
  '002233': ['余振強紀念第二中學、薄扶林花園', 'Yu Chun Keung Memorial College No.2, Pokfulam Gardens'],
  '002234': ['香港華人基督教聯會薄扶林道墳場、啟明寺', 'HKCCCU Pok Fu Lam Road Cemetery, Kai Ming Temple'],
  '002240': ['薄扶林村、職業訓練局薄扶林大樓', 'Pok Fu Lam Village, VTC Pokfulam Complex'],
  '002241': ['淺水灣', 'Repulse Bay'],
  '002252': ['淺水灣', 'Repulse Bay'],
  '002259': ['田灣街、明愛張奧偉國際賓館、南寓', 'Tin Wan Street, Caritas Oswald Cheung International House, South Nest'],
  '002277': ['赤柱村、赤柱市集', 'Stanley Village, Stanley Market'],
  '002281': ['赤柱村、赤柱市場', 'Stanley Village, Stanley Market'],
  '002287': ['大潭郊野公園、大潭童軍中心', 'Tai Tam Country Park, Tai Tam Scout Centre'],
  '002290': ['大潭郊野公園、大潭童軍中心', 'Tai Tam Country Park, Tai Tam Scout Centre'],
  '002294': ['耀中幼教學院、漁映樓', 'Yew Chung College of Early Childhood Education, Yue Ying Lau'],
  '002303': ['香港航海學校、赤柱市場', 'Hong Kong Sea School, Stanley Market'],
  '002306': ['西島中學、甘迺迪中心', 'West Island School, The J.F. Kennedy Centre'],
  '002309': ['西島中學、甘迺迪中心', 'West Island School, The J.F. Kennedy Centre'],
  '002310': ['香港華人基督教聯會薄扶林道墳場', 'HKCCCU Pok Fu Lam Road Cemetery'],
  '002331': ['香港華人基督教聯會薄扶林道墳場', 'HKCCCU Pok Fu Lam Road Cemetery'],
  '002337': ['華富（中）、培英中學', 'Wah Fu (Central), Pui Ying Secondary School'],
  '002345': ['黃竹坑遊樂場、葛量洪醫院、香港仔運動場', 'Wong Chuk Hang Recreation Ground, Grantham Hospital, Aberdeen Sports Ground'],
  '002346': ['葛量洪醫院、香港仔運動場', 'Grantham Hospital, Aberdeen Sports Ground'],
  '002347': ['黃竹坑醫院、葛量洪醫院、海洋公園', 'Wong Chuk Hang Hospital, Grantham Hospital, Ocean Park'],
  '002348': ['黃竹坑醫院、葛量洪醫院、海洋公園', 'Wong Chuk Hang Hospital, Grantham Hospital, Ocean Park'],
  '002350': ['黃竹坑新圍、海洋公園站', 'Wong Chuk Hang San Wai, Ocean Park Station'],
  '002352': ['海洋公園站、黃竹坑新圍', 'Ocean Park Station, Wong Chuk Hang San Wai'],
  '002353': ['香港海洋公園萬豪酒店、海洋公園站', 'Hong Kong Ocean Park Marriott Hotel, Ocean Park Station'],
  '002354': ['黃竹坑體育館、香港仔運動場', 'Wong Chuk Hang Sports Centre, Aberdeen Sports Ground'],
  '002355': ['黃竹坑遊樂場、香港仔運動場、南灣如心酒店', 'Wong Chuk Hang Recreation Ground, Aberdeen Sports Ground, Nina Hotel Island South'],
  '002356': ['業興街、黃竹坑商貿區、南灣如心酒店', 'Yip Hing Street, Wong Chuk Hang Business Area, Nina Hotel Island South'],
  '002357': ['南朗山道、黃竹坑商貿區', 'Nam Long Shan Road, Wong Chuk Hang Business Area'],
  '002365': ['漁光村海鷗樓、香港仔郊野公園', 'Hoy Au Lau Yue Kwong Chuen, Aberdeen Country Park'],
  '002383': ['業興街、黃竹坑商貿區、南灣如心酒店', 'Yip Hing Street, Wong Chuk Hang Business Area, Nina Hotel Island South'],
  '002388': ['田灣街、明愛張奧偉國際賓館、南寓', 'Tin Wan Street, Caritas Oswald Cheung International House, South Nest'],
  '002390': ['南朗山道熟食市場、黃竹坑站、THE SOUTHSIDE', 'Nam Long Shan Road Cooked Food Market, Wong Chuk Hang Station, THE SOUTHSIDE'],
  '002405': ['堅拿道西、時代廣場、銅鑼灣站', 'Canal Road West, Times Square, Causeway Bay Station'],
  '002406': ['摩頓台、香港中央圖書館', 'Moreton Terrace, Hong Kong Central Library'],
  '002414': ['景隆街、銅鑼灣站', 'Cannon Street, Causeway Bay Station'],
  '002417': ['國際調解院（舊灣仔警署）、香港會議展覽中心、會展站', 'International Organization for Mediation (Old Wan Chai Police Station), Hong Kong Convention and Exhibition Centre, Exhibition Centre Station'],
  '002418': ['柯布連道、香港會議展覽中心', 'O\'Brien Road, Hong Kong Convention and Exhibition Centre'],
  '002419': ['六國酒店、入境事務大樓', 'Gloucester Luk Kwok, Immigration Tower'],
  '002420': ['分域街、香港演藝學院', 'Fenwick Street, Hong Kong Academy of Performing Arts'],
  '002421': ['分域街、香港演藝學院', 'Fenwick Street, Hong Kong Academy of Performing Arts'],
  '002423': ['入境事務大樓、香港會議展覽中心', 'Immigration Tower, Hong Kong Convention and Exhibition Centre'],
  '002425': ['香港會議展覽中心、金紫荊廣場', 'HK Convention & Exhibition Centre, Golden Bauhinia Square'],
  '002430': ['盧押道、修頓球場', 'Luard Road, Southorn Playground'],
  '002431': ['柯布連道、灣仔站', 'O\'Brien Road, Wan Chai Station'],
  '002432': ['菲林明道、灣仔站', 'Fleming Road, Wan Chai Station'],
  '002434': ['史釗域道、駱克道市政大廈', 'Stewart Road, Lockhart Road Municipal Services Building'],
  '002435': ['杜老誌道、北海中心', 'Tonnochy Road, CNT Tower'],
  '002436': ['馬師道、時代廣場', 'Marsh Road, Times Square'],
  '002437': ['灣仔消防局、時代廣場、銅鑼灣站', 'Wan Chai Fire Station, Times Square, Causeway Bay Station'],
  '002438': ['銅鑼灣－崇光百貨、銅鑼灣站', 'Causeway Bay - Sogo Department Store, Causeway Bay Station'],
  '002439': ['銅鑼灣－希慎廣場、崇光百貨、銅鑼灣站', 'Causeway Bay - Hysan Place, Sogo Department Store, Causeway Bay Station'],
  '002440': ['堅拿道東、時代廣場', 'Canal Road East, Times Square'],
  '002445': ['菲林明道、灣仔站', 'Fleming Road, Wan Chai Station'],
  '002446': ['修頓球場、灣仔站', 'Southorn Playground, Wan Chai Station'],
  '002447': ['盧押道、修頓球場', 'Luard Road, Southorn Playground'],
  '002448': ['分域街、軒尼詩道', 'Fenwick Street, Hennessy Road'],
  '002451': ['修頓球場、利東街、灣仔站', 'Southorn Playground, Lee Tung Avenue, Wan Chai Station'],
  '002455': ['勿地臣街、時代廣場', 'Matheson Street, Times Square'],
  '002458': ['紀利華木球會、禮頓中心', 'Craigengower Cricket Club, Leighton Centre'],
  '002467': ['立德里、跑馬地馬場、錫克廟', 'Lap Tak Lane, Happy Valley Racecourse, Sikh Temple'],
  '002475': ['利舞臺廣場、時代廣場', 'Lee Theatre Plaza, Times Square'],
  '002480': ['聯發街、灣仔洪聖古廟', 'Lun Fat Street, Wan Chai Hung Shing Temple'],
  '002481': ['廈門街、利東街', 'Amoy Street, Lee Tung Avenue'],
  '002482': ['尚翹峰、藍屋、太源街', 'The Zenith, Blue House, Tai Yuen Street'],
  '002484': ['聖若瑟小學、鄧肇堅醫院', 'St. Joseph\'s Primary School, Tang Shiu Kin Hospital'],
  '002485': ['伊利沙伯體育館、灣仔帝盛酒店、香港麗悅酒店、英皇駿景酒店', 'Queen Elizabeth Stadium, Dorsett Wanchai Hong Kong, Cosmo Hotel Hong Kong, The Emperor Hotel'],
  '002486': ['錫克廟、伊利沙伯體育館、鄧肇堅醫院、灣仔帝盛酒店、麗悅酒店、英皇駿景酒店', 'Khalsa Diwan Sikh Temple, Queen Elizabeth Stadium, Tang Shiu Kin Hospital, Dorsett Wanchai, COSMO hotel, The Emperor Hotel'],
  '002487': ['香港華仁書院、律敦治醫院', 'Wah Yan College Hong Kong, Ruttonjee Hospital'],
  '002488': ['聯發街、灣仔洪聖古廟', 'Lun Fat Street, Wan Chai Hung Shing Temple'],
  '002499': ['白普理小學、景賢里', 'Bradbury School, King Yin Lei'],
  '002500': ['聶歌信山道、司徒拔道瞭望處', 'Mount Nicholson Road, Stubbs Road Lookout'],
  '002501': ['白璧、司徒拔道瞭望處', 'White Jade, Stubbs Road Lookout'],
  '002502': ['灣仔峽道、警隊博物館', 'Wan Chai Gap Road, Police Museum'],
  '002503': ['白璧、司徒拔道瞭望處', 'White Jade, Stubbs Road Lookout'],
  '002504': ['聶歌信山道、司徒拔道瞭望處', 'Mount Nicholson Road, Stubbs Road Lookout'],
  '002514': ['上林、虎豹別墅', 'Serenade, Haw Par Mansion'],
  '002521': ['樂活道、渣甸山花園大廈', 'Broadwood Road, Jardine\'s Lookout Garden Mansion'],
  '002523': ['雅麗閣、瑪利曼小學', 'Elegant Court, Marymount Primary School'],
  '002541': ['大坑道、總站', 'Tai Hang Road, Hong Kong Adventist Hospital'],
  '002544': ['大潭水塘道、黃泥涌水塘公園', 'Tai Tam Reservoir Road, Wong Nai Chung Reservoir Park'],
  '002546': ['怡園、總站', 'Woodland Heights, Hong Kong Adventist Hospital'],
  '002554': ['銅鑼灣－怡和街、銅鑼灣站', 'Causeway Bay - Yee Wo Street, Causeway Bay Station'],
  '002555': ['銅鑼灣－百德新街、崇光百貨、銅鑼灣站', 'Causeway Bay - Paterson Street, Sogo Department Store, Causeway Bay Station'],
  '002556': ['加路連山道、南華體育會', 'Caroline Hill Road, South China Athletic Association'],
  '002557': ['灣仔 (會展新翼)、金紫荊廣場', 'Wan Chai (Convention Centre), Golden Bauhinia Square'],
  '002559': ['灣仔碼頭、會展站', 'Wan Chai Ferry Pier, Exhibition Centre Station'],
  '002561': ['維多利亞公園、皇室堡', 'Victoria Park, Windsor House'],
  '002564': ['杜老誌道、灣仔運動場', 'Tonnochy Road, Wan Chai Sports Ground'],
  '002567': ['禮頓中心、時代廣場', 'Leighton Centre, Times Square'],
  '002568': ['百德新街、世貿中心', 'Paterson Street, World Trade Centre'],
  '002569': ['胡忠大廈、合和中心', 'Wu Chung House, Hopewell Centre'],
  '002570': ['伊利莎伯大廈、銅鑼灣購物區', 'Elizabeth House, Causeway Bay Shopping Area'],
  '002572': ['史釗域道、駱克道市政大廈', 'Stewart Road, Lockhart Road Municipal Services Building'],
  '002574': ['銅鑼灣－百德新街、崇光百貨、銅鑼灣站', 'Causeway Bay - Paterson Street, Sogo Department Store, Causeway Bay Station'],
  '002580': ['富怡道、小西灣綜合大樓、富怡花園', 'Fu Yee Road, Siu Sai Wan Complex, Cheerful Garden'],
  '002593': ['南昌站、富昌邨', 'Nam Cheong Station, Fu Cheong Estate'],
  '002595': ['麗閣邨、長沙灣邨', 'Lai Kok Estate, Cheung Sha Wan Estate'],
  '002598': ['屯門兆麟政府綜合大樓、胡陳金枝中學', 'Tuen Mun Siu Lun Government Complex, Mrs Aw Boon Haw Secondary School'],
  '002601': ['屯門官立中學、新都大廈、華都花園', 'Tuen Mun Government Secondary School, New Town Mansion, Waldorf Garden'],
  '002602': ['屯門官立中學、新都大廈、華都花園', 'Tuen Mun Government Secondary School, New Town Mansion, Waldorf Garden'],
  '002616': ['深井村、麗都花園', 'Sham Tseng Village, Lido Garden'],
  '002617': ['深井村、麗都花園', 'Sham Tseng Village, Lido Garden'],
  '002619': ['碧堤半島、海韻花園', 'Bellagio, Rhine Garden'],
  '002620': ['嘉湖山莊景湖居、嘉湖海逸酒店', 'Kenswood Court Kingswood Villas, Harbour Plaza Resort City'],
  '002622': ['香港濕地公園、俊宏軒', 'Hong Kong Wetland Park, Grandeur Terrace'],
  '002623': ['香港濕地公園、俊宏軒', 'Hong Kong Wetland Park, Grandeur Terrace'],
  '002627': ['北京道、香港文化中心', 'Peking Road, Hong Kong Cultural Centre'],
  '002630': ['九龍公園徑、1881', 'Kowloon Park Drive, 1881'],
  '002657': ['國泰城（東）、機場風鈴徑', 'Cathay Pacific City (East), Airport Golden Trumpet Trail'],
  '002669': ['天逸邨逸洋樓、天富苑', 'Yat Yeung House Tin Yat Estate, Tin Fu Court'],
  '002672': ['亞洲國際博覽館、麗豪航天城酒店', 'AsiaWorld-Expo, Regala Skycity Hotel'],
  '002677': ['模範邨、北角海逸酒店', 'Model Housing Estate, Harbour Plaza North Point'],
  '002707': ['泄蘭街、煤氣路燈、香港動植物公園', 'Zetland Street, Gas Lamps, Hong Kong Zoological and Botanical Gardens'],
  '002710': ['映灣園四期、東涌北公園中藥園', 'Caribbean Coast Phase 4, Tung Chung North Park, Chinese Herb Garden'],
  '002713': ['銅鑼灣－糖街、柏寧酒店、富豪香港酒店、香港逸蘭銅鑼灣酒店、怡和街、崇光百貨', 'Causeway Bay - Sugar Street, The Park Lane, Regal Hong Kong Hotel, Lanson Place Causeway Bay, Hong Kong, Yee Wo Street, Sogo Department Store'],
  '002715': ['機場 (2 號客運大樓)', 'Airport (Terminal 2)'],
  '002716': ['花園街街市、旺角道', 'Fa Yuen Street Market, Mong Kok Road'],
  '002720': ['何文田廣場、香港都會大學', 'Homantin Plaza, Hong Kong Metropolitian University'],
  '002721': ['迦密村街、何文田政府合署', 'Carmel Village Street, Ho Man Tin Government Offices'],
  '002726': ['欣圖軒、何文田政府合署', 'Cascades, Ho Man Tin Government Offices'],
  '002734': ['西區警署、瑧璈', 'Western Police Station, Bohemian House'],
  '002736': ['德忌利士街、中環站、香港站', 'Douglas Street, Central Station, Hong Kong Station'],
  '002745': ['卑利街、元創方', 'Peel Street, PMQ'],
  '002746': ['嘉賢大廈、雅翠園', 'Alpine Court, Emerald Gardens'],
  '002748': ['嘉賢大廈、雅翠園', 'Alpine Court, Emerald Gardens'],
  '002759': ['皇后街、帝后華庭', 'Queen’s Street, Queen\'s Terrace'],
  '002761': ['花園道、花園道山頂纜車總站', 'Garden Road, Garden Road (Peak Tram Terminus)'],
  '002762': ['雲咸街、蘭桂坊', 'Wyndham Street, Lan Kwai Fong'],
  '002772': ['柴灣工廠邨、新翠花園、柴灣站', 'Chai Wan Industrial Estate, New Jade Garden, Chai Wan Station'],
  '002776': ['基利路、栢蕙苑、南豐新邨', 'Greig Road, Parkvale, Nan Fung San Chuen'],
  '002778': ['灣景園、柴灣健康院', 'Bayview Park, Chai Wan Health Centre'],
  '002790': ['小西灣運動場、藍灣半島', 'Siu Sai Wan Sports Ground, Island Resort'],
  '002804': ['華人永遠墳場、靈灰閣、天主教聖十字架墳場', 'Chinese Permanent Cemetery, Columbarium, Holy Cross Catholic Cemetery'],
  '002807': ['歌連臣角火葬場、石澳道', 'Cape Collinson Crematorium, Shek O Road'],
  '002810': ['怡靖苑、長沙灣政府合署', 'Yee Ching Court, Cheung Sha Wan Government Offices'],
  '002811': ['白加士街、廟街', 'Parkes Street, Temple Street'],
  '002813': ['寶熙苑、李鄭屋邨', 'Po Hei Court, Lei Cheng Uk Estate'],
  '002815': ['福榮街、高登電腦中心、黃金電腦商場', 'Fuk Wing Street, Golden Computer Centre, Golden Computer Arcade'],
  '002816': ['D2 Place ONE、大南西街', 'D2 Place ONE, Tai Nan West Street'],
  '002817': ['銀行中心、奶路臣街、旺角站', 'Bank Centre, Nelson Street, Mong Kok Station'],
  '002835': ['協和小學、旺角花墟', 'Heep Woh Primary School, Mong Kok Flower Market'],
  '002838': ['戲曲中心、香港皇家太平洋酒店', 'Xiqu Centre, Royal Pacific Hotel'],
  '002849': ['西洋菜南街、旺角站、旺角中心', 'Sai Yeung Choi Street South, Mong Kok Station, Argyle Centre'],
  '002850': ['櫸樹街、新九龍廣場', 'Beech Street, New Kowloon Plaza'],
  '002851': ['花園街街市、旺角道', 'Fa Yuen Street Market, Mong Kok Road'],
  '002854': ['南昌站、富昌邨', 'Nam Cheong Station, Fu Cheong Estate'],
  '002862': ['柯士甸站、高鐵西九龍站', 'Austin Station, HSR West Kowloon Station'],
  '002878': ['帝柏海灣、奧海城2期', 'Central Park, Olympian City 2'],
  '002880': ['凱德苑、發祥街西、西九龍法院大樓', 'Hoi Tak Court, Fat Tseung Street West, West Kowloon Law Courts Building'],
  '002881': ['泓景臺、昇悅居、宇晴軒', 'Banyan Garden, Liberte, The Pacifica'],
  '002882': ['海達邨、東京街西、西九龍法院大樓', 'Hoi Tat Estate, Tonkin Street West, West Kowloon Law Courts Building'],
  '002884': ['大南街、西九龍中心', 'Tai Nan Street, Dragon Centre'],
  '002887': ['東京街、宇宙商場', 'Tonkin Street, Apollo Shopping Center'],
  '002888': ['山東街', 'Shantung Street'],
  '002890': ['泓景臺、昇悅居、宇晴軒', 'Banyan Garden, Liberte, The Pacifica'],
  '002906': ['TKO Spot、尚德', 'TKO Spot, Sheung Tak'],
  '002907': ['將軍澳醫院主座大樓、坑口（北）', 'Tseung Kwan O Hospital Main Block, Hang Hau (North)'],
  '002908': ['欣明苑、新都城二期、寶琳站', 'Yan Ming Court, Metro City II, Po Lam Station'],
  '002910': ['明德邨、將軍澳醫院', 'Ming Tak Estate, Tseung Kwan O Hospital'],
  '002911': ['將軍澳醫院主座大樓、坑口（北）', 'Tseung Kwan O Hospital Main Block, Hang Hau (North)'],
  '002913': ['調景嶺站、香港知專設計學院', 'Tiu Keng Leng Station, Hong Kong Design Institute'],
  '002918': ['將軍澳站、香港九龍東智選假日酒店、香港九龍東皇冠假日酒店', 'Tseung Kwan O Station, Holiday Inn Express HK Kowloon East, Crowne Plaza HK Kowloon East'],
  '002919': ['峻瀅、日出康城首都、海茵莊園', 'The Beaumount, The Capitol LOHAS Park, Manor Hill'],
  '002920': ['MEGA Plus 數據中心、日出康城領都', 'MEGA Plus Data Centre, Le Prestige LOHAS Park'],
  '002921': ['數據技術中心、大赤沙消防局', 'Data Technology Hub (DT Hub), Tai Chik Sha Fire Station'],
  '002930': ['邵氏影城、百勝角、香港中醫醫院', 'Shaw Studios, Pak Shing Kok, The Chinese Medicine Hospital of Hong Kong'],
  '002933': ['佛教志蓮小學、富康花園、君傲灣、將軍澳站', 'Chi Lin Buddhist Primary School, Beverly Garden, The Grandiose, Tseung Kwan O Station'],
  '002941': ['土地灣、龍脊', 'To Tei Wan, Dragon\'s Back'],
  '002952': ['土地灣、龍脊', 'To Tei Wan, Dragon\'s Back'],
  '002962': ['景隆街、銅鑼灣站', 'Cannon Street, Causeway Bay Station'],
  '002964': ['香港會議展覽中心、金紫荊廣場', 'HK Convention & Exhibition Centre, Golden Bauhinia Square'],
  '002979': ['淘大花園、東九文化中心', 'Amoy Gardens, East Kowloon Cultural Centre'],
  '002990': ['馬頭角道、新山道', 'Ma Tau Kok Road, San Shan Road'],
  '002993': ['黃大仙下邨龍慧樓、黃大仙站', 'Lung Wai House, Lower Wong Tai Sin Estate, Wong Tai Sin Station'],
  '002996': ['何文田站、忠孝街', 'Ho Man Tin Station, Chung Hau Street'],
  '002998': ['海底隧道巴士轉乘站、香港理工大學、紅磡站', 'Cross Harbour Tunnel Bus-Bus Interchange, The Hong Kong Polytechnic University, Hung Hom Station'],
  '003003': ['何文田廣場、香港都會大學', 'Homantin Plaza, Hong Kong Metropolitan University'],
  '003012': ['喇沙利道、聖德肋撒醫院', 'La Salle Road, St. Teresa\'s Hospital'],
  '003030': ['馬頭角道、新山道', 'Ma Tau Kok Road, San Shan Road'],
  '003031': ['淘大花園、東九文化中心', 'Amoy Gardens, East Kowloon Cultural Centre'],
  '003042': ['秀雅道遊樂場、曉晴閣', 'Sau Nga Road Playground, Hiu Ching House'],
  '003054': ['觀音街、家維邨、逸 • 酒店', 'Kun Yam Street, Ka Wai Chuen, Hotel sáv'],
  '003055': ['何文田廣場、香港都會大學', 'Homantin Plaza, Hong Kong Metropolitan University'],
  '003056': ['創紀之城、牛頭角站', 'Millennium City, Ngau Tau Kok Station'],
  '003058': ['九龍城警署、香港眼科醫院、九龍城法院大樓', 'Kowloon City Police Station, Hong Kong Eye Hospital, Kowloon City Law Courts Building'],
  '003059': ['雅麗居、九龍醫院康復大樓', 'The Astrid, Kowloon Hospital Rehabilitation Building'],
  '003061': ['醫院管理局大樓、九龍醫院康復大樓', 'Hospital Authority Building, Kowloon Hospital Rehabilitation Building'],
  '003062': ['香港眼科醫院、九龍城法院大樓', 'Hong Kong Eye Hospital, Kowloon City Law Courts Building'],
  '003065': ['又一城、九龍塘站', 'Festival Walk, Kowloon Tong Station'],
  '003079': ['新界鄉議局大樓、濱景花園、香港沙田萬怡酒店', 'Heung Yee Kuk New Territories Building, Ravana Garden, Courtyard by Marriott Hong Kong Sha Tin'],
  '003083': ['錦龍苑、利安邨', 'Kam Lung Court, Lee On Estate'],
  '003085': ['沙田第一城第27座、寶城街', 'Block 27 City One Shatin, Po Shing Street'],
  '003086': ['濱景花園、香港沙田萬怡酒店', 'Ravana Garden, Courtyard by Marriott Hong Kong Sha Tin'],
  '003087': ['海柏花園、馬鞍山廣場、新港城中心、馬鞍山站', 'Bayshore Towers, Ma On Shan Plaza, MOSTown, Ma On Shan Station'],
  '003091': ['錦龍苑、利安邨', 'Kam Lung Court, Lee On Estate'],
  '003111': ['綠悠雅苑、青怡花園', 'Greenview Villa, Tsing Yi Garden'],
  '003126': ['綠悠雅苑、青怡花園', 'Greenview Villa, Tsing Yi Garden'],
  '003138': ['長青商場、藍澄灣', 'Cheung Ching Commercial Complex, Rambler Crest'],
  '003139': ['長青商場、藍澄灣', 'Cheung Ching Commercial Complex, Rambler Crest'],
  '003150': ['栢麗購物大道、聖安德烈堂', 'Park Lane Shopper\'s Boulevard, St. Andrew\'s Church'],
  '003152': ['文明里、油麻地站', 'Man Ming Lane, Yau Ma Tei Station'],
  '003153': ['新墟街市、天生樓', 'San Hui Market, The Parkville'],
  '003159': ['將軍澳運動場、香港單車館、將軍澳廣場', 'Tseung Kwan O Sports Ground, Hong Kong Velodrome, Tseung Kwan O Plaza'],
  '003160': ['蓬萊路、清水灣半島', 'Pung Loi Road, Oscar By The Sea'],
  '003194': ['屯門碼頭、海翠花園', 'Tuen Mun Ferry Pier, Pierhead Garden'],
  '003196': ['翠寧花園、豐景園', 'Tsui Ning Garden, Goodview Garden'],
  '003201': ['輕鐵鳴琴站、山景邨', 'LR Ming Kum Stop, Shan King Estate'],
  '003204': ['大興體育館、大興邨', 'Tai Hing Sports Centre, Tai Hing Estate'],
  '003206': ['麒麟圍、屯門醫院', 'Kei Lun Wai, Tuen Mun Hospital'],
  '003207': ['欣田邨、紫田村', 'Yan Tin Estate, Tsz Tin Tsuen'],
  '003209': ['欣田邨、兆康苑、紫田村', 'Yan Tin Estate, Siu Hong Court, Tsz Tin Tsuen'],
  '003210': ['兆康苑兆賢閣、麒麟圍', 'Siu Yin House, Siu Hong Court, Kei Lun Wai'],
  '003212': ['青松觀、建生邨', 'Ching Chung Koon, Kin Sang Estate'],
  '003213': ['大興體育館、大興邨', 'Tai Hing Sports Centre, Tai Hing Estate'],
  '003220': ['翠寧花園、豐景園', 'Tsui Ning Garden, Goodview Garden'],
  '003225': ['邵氏影城、百勝角、香港中醫醫院', 'Shaw Studios, Pak Shing Kok, The Chinese Medicine Hospital of Hong Kong'],
  '003233': ['牛頭角站、創紀之城', 'Ngau Tau Kok Station, Millennium City'],
  '003244': ['太和廣場、太和站', 'Tai Wo Plaza, Tai Wo Station'],
  '003247': ['太和廣場、太和站', 'Tai Wo Plaza, Tai Wo Station'],
  '003251': ['北角官立小學、鰂魚涌站', 'North Point Government Primary School, Quarry Bay Station'],
  '003253': ['西消防街、中山紀念公園', 'Western Fire Services Street, Sun Yat Sen Memorial Park'],
  '003257': ['新圍苑、良景邨、輕鐵新圍站L', 'San Wai Court, Leung King Estate, LR San Wai Stop L'],
  '003258': ['兆邦苑、輕鐵田景站L', 'Siu Pong Court, LR Tin King Stop L'],
  '003259': ['寶田邨、屯門西北游泳池', 'Po Tin Estate, Tuen Mun North West Swimming Pool'],
  '003261': ['富泰商場、嶺南大學商學院', 'Fu Tai Shopping Centre, Lingnan University Faculty of Business'],
  '003262': ['富泰商場、嶺南大學商學院', 'Fu Tai Shopping Centre, Lingnan University Faculty of Business'],
  '003263': ['寶怡花園、建生邨', 'Blossom Garden, Kin Sang Estate'],
  '003264': ['盈豐園、寶田邨、建生邨、屯門西北游泳池', 'Goodrich Garden, Po Tin Estate, Kin Sang Estate, Tuen Mun North West Swimming Pool'],
  '003266': ['田景邨田裕樓、新圍苑、輕鐵新圍站L', 'Tin Yue House, Tin King Estate, San Wai Court, LR San Wai Stop L'],
  '003269': ['海韻軒、紅樂道', 'Harbourview Horizon, Hung Lok Road'],
  '003277': ['楊屋道街市、荃新天地、如心廣場、荃灣市中心', 'Yeung Uk Road Market, Citywalk, Nina Tower, Tsuen Wan Town Centre'],
  '003279': ['富祐大廈、鳳鑽苑', 'Fu Yau Building, Fung Chuen Court'],
  '003280': ['蒲慈里、慈樂邨', 'Po Tsz Lane, Tsz Lok Estate'],
  '003281': ['蒲蘅里、蒲崗村道體育館', 'Po Hang Lane, Po Kong Village Road Sports Centre'],
  '003284': ['新蒲崗、四美街', 'San Po Kong, Sze Mei Street'],
  '003287': ['興和街、漁映樓', 'Hing Wo Street, Yue Ying Lau'],
  '003299': ['柯士甸道西、西九文化區', 'Austin Road West, West Kowloon Cultural District'],
  '003300': ['灣仔 (會展新翼)、金紫荊廣場', 'Wan Chai (Convention Centre), Golden Bauhinia Square'],
  '003301': ['星光大道、永安廣場', 'Avenue of Stars, Wing On Plaza'],
  '003302': ['星光大道、永安廣場', 'Avenue of Stars, Wing On Plaza'],
  '003303': ['欽州街、長沙灣政府合署', 'Yen Chow Street, Cheung Sha Wan Government Offices'],
  '003305': ['香港東樹木組、愛秩序灣', 'Hong Kong East Tree Team, Aldrich Bay'],
  '003333': ['楊屋道街市、荃新天地、如心廣場、荃灣市中心', 'Yeung Uk Road Market, Citywalk, Nina Tower, Tsuen Wan Town Centre'],
  '003337': ['政府總部、金鐘站', 'Central Government Offices, Admiralty Station'],
  '003339': ['中環（香港摩天輪）、維多利亞港', 'Central (Hong Kong Observation Wheel), Victoria Harbour'],
  '003344': ['烏溪沙村、利安邨', 'Wu Kai Sha Village, Lee On Estate'],
  '003346': ['烏溪沙村、利安邨', 'Wu Kai Sha Village, Lee On Estate'],
  '003348': ['欣安邨、錦柏苑', 'Yan On Estate, Kam Pak Court'],
  '003352': ['山西街、冠山苑、高山劇場', 'Shansi Street, Kwun Shan Court, Ko Shan Theatre'],
  '003366': ['宏通街、MegaBox', 'Wang Tung Street, Megabox'],
  '003372': ['花都廣場、華明邨、華心邨', 'Flora Plaza, Wah Ming Estate, Wah Sum Estate'],
  '003374': ['蓬瀛仙館、粉嶺站', 'Fung Ying Seen Koon, Fanling Station'],
  '003390': ['小瀝源、綠怡雅苑', 'Siu Lek Yuen, Greenhill Villa'],
  '003395': ['1號客運大樓（南）', 'Terminal 1 (South)'],
  '003408': ['聚魚道、港灣豪庭', 'Chui Yu Road, Metro Harbour View'],
  '003413': ['新墟街市、天生樓', 'San Hui Market, The Parkville'],
  '003415': ['會展站、灣仔碼頭', 'Exhibition Centre Station, Wan Chai Ferry Pier'],
  '003418': ['龍德街、環宇海灣、海灣花園、海濱花園、柏傲灣', 'Lung Tak Street, City Point, Waterside Plaza, Riviera Gardens, The Pavilia Bay'],
  '003419': ['龍德街、環宇海灣、海灣花園、海濱花園、柏傲灣', 'Lung Tak Street, City Point, Waterside Plaza, Riviera Gardens, The Pavilia Bay'],
  '003423': ['小瀝源、綠怡雅苑', 'Siu Lek Yuen, Greenhill Villa'],
  '003437': ['輕鐵洪水橋站、溱林、蔚林', 'LR Hung Shui Kiu Stop, The Woodsville, The Woodside'],
  '003442': ['博康邨、沙田圍站', 'Pok Hong Estate, Sha Tin Wai Station'],
  '003443': ['東環 (迎禧路)、昇薈', 'Century Link (Ying Hei Road), The Visionary'],
  '003452': ['昇薈、東環', 'The Visionary, Century Link'],
  '003453': ['迎東邨、翔東邨翔日樓', 'Ying Tung Estate, Cheung Yat House Cheung Tung Estate'],
  '003454': ['昇薈、東環', 'The Visionary, Century Link'],
  '003472': ['播道書院、雍明苑', 'Evangel College, Yung Ming Court'],
  '003473': ['播道書院、雍明苑', 'Evangel College, Yung Ming Court'],
  '003474': ['藍塘傲、將軍澳政府合署', 'Alto Residences, Tseung Kwan O Government Offices'],
  '003475': ['天晉III、將軍澳海濱公園', 'The Wings III, Tseung Kwan O Waterfront Park'],
  '003477': ['寶盈花園、將軍澳站', 'Bauhinia Garden, Tseung Kwan O Station'],
  '003481': ['天晴邨晴碧樓、悅品天秀酒店．元朗', 'Ching Pik House Tin Ching Estate, Hotel COZi．Wetland'],
  '003484': ['掃管笏、OMA OMA', 'So Kwun Wat, OMA OMA'],
  '003505': ['沐虹街、啟晴邨', 'Muk Hung Street, Kai Ching Estate'],
  '003509': ['油麻地消防局、現時點、油麻地站', 'Yau Ma Tei Fire Station, In\'s Point, Yau Ma Tei Station'],
  '003510': ['上海街、油麻地戲院、油麻地果欄', 'Shanghai Street, Yau Ma Tei Theatre, Yau Ma Tei Wholesale Fruit Market'],
  '003511': ['奧運站、滙豐中心', 'Olympic Station, HSBC Centre'],
  '003512': ['君匯港、大同新邨', 'Harbour Green, Cosmopolitan Estates'],
  '003513': ['廣東道、油麻地戲院、油麻地果欄', 'Canton Road, Yau Ma Tei Theatre, Yau Ma Tei Wholesale Fruit Market'],
  '003514': ['青年會、現時點、油麻地站', 'YMCA, In\'s Point, Yau Ma Tei Station'],
  '003518': ['西九龍法院大樓、富昌邨', 'West Kowloon Law Courts Building, Fu Cheong Estate'],
  '003520': ['Miami Quay、維港1號', 'Miami Quay, One Victoria'],
  '003522': ['侯王道、宋皇臺站', 'Hau Wong Road, Sung Wong Toi Station'],
  '003532': ['侯王道、宋皇臺站', 'Hau Wong Road, Sung Wong Toi Station'],
  '003533': ['雅翔道（西區海底隧道收費廣場）', 'Nga Cheung Road (Western Harbour Crossing Toll Plaza)'],
  '003535': ['Miami Quay、維港1號', 'Miami Quay, One Victoria'],
  '003536': ['馬頭圍邨、盛德街', 'Ma Tau Wai Estate, Shing Tak Street'],
  '003537': ['德朗邨、麗晶花園', 'Tak Long Estate, Richland Gardens'],
  '003544': ['海盈邨、凱樂苑', 'Hoi Ying Estate, Hoi Lok Court'],
  '003548': ['高鐵西九龍站上落客區、柯士甸站', 'HSR West Kowloon Station Boarding and Alighting Area, Austin Station'],
  '003559': ['香港文化中心、香港太空館', 'Hong Kong Cultural Centre, Hong Kong Space Museum'],
  '003560': ['瀝源邨、源禾路體育館', 'Lek Yuen Estate, Yuen Wo Road Sports Centre'],
  '003561': ['禾輋邨、沙田運動場', 'Wo Che Estate, Sha Tin Sports Ground'],
  '003562': ['禾輋邨、沙田運動場', 'Wo Che Estate, Sha Tin Sports Ground'],
  '003563': ['瀝源邨、源禾路體育館', 'Lek Yuen Estate, Yuen Wo Road Sports Centre'],
  '003580': ['美華工業中心、翔龍灣', 'Merit Industrial Centre, Grand Waterfront'],
  '003582': ['雲海、星漣海、城大學生宿舍', 'St. Barths, Seanorama, CityU Student Residence (Ma On Shan)'],
  '003588': ['民航處總部、國泰坊、中航大廈', 'CAD Headquarters, Cathay House, CNAC House'],
  '003590': ['觀塘碼頭、開源道', 'Kwun Tong Ferry, Hoi Yuen Road'],
  '003596': ['西洋菜南街、旺角站、旺角中心', 'Sai Yeung Choi Street South, Mong Kok Station, Argyle Centre'],
  '003597': ['通菜街、先達廣場、SKYPARK、旺角站', 'Tung Choi Street, Sincere Podium, SKYPARK, Mong Kok Station'],
  '003598': ['如心廣場、海之戀、荃灣西站', 'Nina Tower, Ocean Pride, Tsuen Wan West Station'],
  '003608': ['灝景灣、長安邨', 'Villa Esplanada, Cheung On Estate'],
  '003615': ['下高埔村、爾巒', 'Ha Ko Po Tsuen, Riva'],
  '003618': ['沙埔村、峻巒', 'Sha Po Tsuen, Park Yoho'],
  '003628': ['沙埔村、峻巒', 'Sha Po Tsuen, Park Yoho'],
  '003631': ['下高埔村、爾巒', 'Ha Ko Po Tsuen, Riva'],
  '003638': ['沙田大會堂、沙田中心、新城市廣場二期、沙田站', 'Sha Tin Town Hall, Shatin Centre, New Town Plaza Phase 2, Sha Tin Station'],
  '003639': ['帝都酒店、新城市廣場三期、希爾頓中心', 'Royal Park Hotel, New Town Plaza Phase 3, Hilton Plaza'],
  '003649': ['輕鐵洪水橋站、溱林、蔚林', 'LR Hung Shui Kiu Stop, The Woodsville, The Woodside'],
  '003657': ['屯仁街、屯門市廣場', 'Tuen Yan Street, Tuen Mun Town Plaza'],
  '003685': ['蔬菜統營處、麗翠苑', 'Vegetable Marketing Organization, Lai Tsui Court'],
  '003691': ['拔萃男書院、花墟公園、旺角大球場', 'Diocesan Boys\' School, Fa Hui Park, Mong Kok Stadium'],
  '003692': ['太子站、聯合廣場', 'Prince Edward Station, Allied Plaza'],
  '003694': ['警察體育遊樂會、旺角花墟', 'Police Sports and Recreation Club, Mong Kok Flower Market'],
  '003699': ['D2 Place ONE、大南西街', 'D2 Place ONE, Tai Nan West Street'],
  '003707': ['雅翔道（西區海底隧道收費廣場）', 'Nga Cheung Road (Western Harbour Crossing Toll Plaza)'],
  '003711': ['四美街、啟翔苑、采頤花園', 'Sze Mei Street, Kai Cheung Court, Rhythm Garden'],
  '003724': ['粉嶺站 - A2 出口、粉嶺名都、粉嶺中心、祥華邨', 'Fanling Station - Exit A2, Fanling Town Centre, Fanling Centre, Cheung Wah Estate'],
  '003727': ['乙明邨、沙角邨', 'Jat Min Chuen, Sha Kok Estate'],
  '003730': ['乙明邨、沙角邨', 'Jat Min Chuen, Sha Kok Estate'],
  '003732': ['御海灣、南浪海灣、兆翠苑', 'Regency Bay, Nerine Cove, Siu Tsui Court'],
  '003733': ['御海灣、南浪海灣、兆翠苑', 'Regency Bay, Nerine Cove, Siu Tsui Court'],
  '003749': ['白石角、天賦海灣', 'Pak Shek Kok, Providence Bay'],
  '003753': ['NOVO LAND、塘亨路', 'NOVO LAND, Tong Hang Road'],
  '003757': ['輕鐵鳴琴站、山景邨', 'LR Ming Kum Stop, Shan King Estate'],
  '003760': ['菁田邨、欣寶路簡約公屋', 'Ching Tin Estate, Yan Po Road Light Public Housing'],
  '003767': ['NOVO LAND、塘亨路', 'NOVO LAND, Tong Hang Road'],
  '003772': ['西九文化區、M+、香港故宮文化博物館', 'West Kowloon Cultural District, M+, Hong Kong Palace Museum'],
  '003788': ['偉樂街、麗港城、茶果嶺海濱公園', 'Wai Lok Street, Laguna City, Cha Kwo Ling Promenade'],
  '003790': ['柏蔚森、啟航1331', 'The Pavilia Forest, Runway 1331'],
  '003796': ['紅磡站、都會海逸酒店', 'Hung Hom Station, Harbour Plaza Metropolis'],
  '003797': ['翠怡花園、太和邨', 'Greenery Plaza, Tai Wo Estate'],
  '003813': ['藍田綜合大樓、藍田 (北)', 'Lam Tin Complex, Lam Tin (North)'],
  '003815': ['裕雅商場、香港東涌世茂喜來登酒店、香港東涌福朋喜來登酒店', 'Yu Nga Shopping Centre, Sheraton HK Tung Chung Hotel, Four Points by Sheraton HK Tung Chung'],
  '003817': ['順欣花園、天平邨、上水名都', 'Sunningdale Garden, Tin Ping Estate, Sheung Shui Town Centre'],
  '003819': ['邁亞美海灣、慧豐園', 'Miami Beach Towers, Marina Garden'],
  '003820': ['茶果嶺道變電站、成業街', 'Cha Kwo Ling Road Substation, Shing Yip Street'],
  '003827': ['啟翔苑、采頤花園', 'Kai Cheung Court, Rhythm Garden'],
  '003828': ['泥涌、西澳', 'Nai Chung, Sai O'],
  '003829': ['輋下、官坑', 'Che Ha, Kwun Hang'],
  '003830': ['馬牯纜、大洞、田寮', 'Ma Kwu Lam, Tai Tung, Tin Liu'],
  '003831': ['西沙GO PARK、井頭', 'GO PARK Sai Sha, Tseng Tau'],
  '003832': ['田寮、馬牯纜、大洞', 'Tin Liu, Ma Kwu Lam, Tai Tung'],
  '003833': ['輋下、官坑', 'Che Ha, Kwun Hang'],
  '003834': ['西澳、泥涌', 'Sai O, Nai Chung'],
  '003836': ['駿業街、觀塘碼頭', 'Tsun Yip Street, Kwun Tong Ferry'],
  '003837': ['駿業街、觀塘碼頭', 'Tsun Yip Street, Kwun Tong Ferry'],
  '003844': ['金鐘－港鐵 D 出口、太古廣場', 'Admiralty - MTR Exit D, Pacific Place'],
  '003845': ['金鐘－金鐘廊、太古廣場', 'Admiralty - Queensway Plaza, Pacific Place'],
  '003848': ['龍逸邨、業旺邨', 'Lung Yat Estate, Yip Wong Estate'],
  '003850': ['錦駿苑', 'Kam Chun Court'],
  '003851': ['錦駿苑', 'Kam Chun Court'],
  '003853': ['大埔超級城、大埔中心', 'Tai Po Mega Mall, Tai Po Centre'],
  '003855': ['大埔超級城、大埔中心', 'Tai Po Mega Mall, Tai Po Centre'],
  '003856': ['啟德－天璽．天、雙子匯', 'Kai Tak - Cullinan Sky, The Twins Tower'],
  '003864': ['富亨邨、大元邨', 'Fu Heng Estate, Tai Yuen Estate'],
  '003879': ['K11人文購物藝術館、尖東站、星光大道', 'K11 MUSEA, East Tsim Sha Tsui Station, Avenue of Stars'],
  '003888': ['德福大廈、德福花園', 'Telford House, Telford Gardens'],
  '003890': ['維港．灣畔、澐璟', 'Victoria Voyage, Pano Harbour'],
  '003891': ['Double Coast、啟德橋道', 'Double Coast, Kai Tak Bridge Road'],
  '003897': ['柯士甸站、高鐵西九龍站', 'Austin Station, HSR West Kowloon Station'],
  '003901': ['Double Coast、啟德橋道', 'Double Coast, Kai Tak Bridge Road'],
  '003907': ['柏蔚森、啟航1331', 'The Pavilia Forest, Runway 1331'],
  '003908': ['德福大廈、德福花園', 'Telford House, Telford Gardens'],
  '003911': ['中電總部、香港啟德帝盛酒店、啟德體育園', 'CLP Headquarters, Dorsett Kai Tak Hong Kong, Kai Tak Sports Park'],
  '003917': ['深水埗公園、深水埗公園游泳池、西九龍法院大樓', 'Sham Shui Po Park, Sham Shui Po Park Swimming Pool, West Kowloon Law Courts Building'],
  '003932': ['宋皇臺站 －D出口、啟悅苑', 'Sung Wong Toi Station - Exit D, Kai Yuet Court'],
  '003933': ['啟德簡約公屋、啟欣苑', 'Kai Tak Light Public Housing, Kai Yan Court'],
  '003934': ['啟德簡約公屋、啟欣苑', 'Kai Tak Light Public Housing, Kai Yan Court'],
  '003935': ['宋皇臺站 －D出口、啟悅苑', 'Sung Wong Toi Station - Exit D, Kai Yuet Court'],
  '003950': ['迎東邨、翔東邨翔日樓', 'Ying Tung Estate, Cheung Yat House Cheung Tung Estate'],
  '003966': ['裕民坊、觀塘站', 'Yue Man Square (YM2), Kwun Tong Station'],
  '003967': ['裕民坊、凱滙', 'Yue Man Square (YM2), Grand Central'],
  '003968': ['香港仔隧道巴士轉乘站、港怡醫院', 'Aberdeen Tunnel Bus-Bus Interchange, Gleneagles Hong Kong Hospital'],
  '003969': ['香港仔隧道巴士轉乘站、港怡醫院', 'Aberdeen Tunnel Bus-Bus Interchange, Gleneagles Hong Kong Hospital'],
  '003999': ['啟德醫院-專科門診大樓 (四座)', 'Kai Tak Hospital - Specialist Out-patient Clinic Block (Tower 4)'],
  '004000': ['啟德醫院-專科門診大樓 (四座)', 'Kai Tak Hospital - Specialist Out-patient Clinic Block (Tower 4)'],
};
